app/models/order.py
from . import db
from datetime import datetime

class Order(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    allergies = db.Column(db.String(200), nullable=False, default='none')
    dietary_restriction = db.Column(db.String(200), nullable=False, default='none')
    status = db.Column(db.String(20), nullable=False, default='pending')
    delivery = db.Column(db.Boolean, nullable=False, default=False)  # True if delivery, False if pickup
    location = db.Column(db.String(200),nullable=False, default='UIC')  # Location for delivery orders
    request_time = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    dispense_time = db.Column(db.DateTime,nullable=True)  # Dispense time for completed orders

    
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = db.relationship('User', backref=db.backref('orders', lazy=True))
    
    
    @classmethod
    def get_order_count(cls):
        return cls.query.count()

app/controllers/order_controller.py
from flask import render_template, Blueprint, request, redirect, url_for, session, flash, jsonify
from ..models.user import User, db
from ..models.order import Order
from ..ults._emailAPI import register_email, order_email, order_accepted_email, order_denied_email
from datetime import datetime



# from app import app

order_controller = Blueprint("order_controller", __name__)

@order_controller.route('/order_request', methods=['POST'])
def order_request():
    user_id = session.get('user_id')
    # retrive data from request form
    allergies = request.form.getlist('allergies')
    dietary_restrictions = request.form.getlist('dietary_restriction')
    delivery_str = request.form.get('delivery')
    
    if delivery_str == '0':
        delivery = False
    else:
        delivery = True
    # Debug statements to check the value of location   
    if delivery == 0:
        location = "UIC"
    else:
        location = request.form.get('location')
            
    allergies_str = ', '.join(allergies) if allergies else 'none'
    dietary_restrictions_str = ', '.join(dietary_restrictions) if dietary_restrictions else 'none'
    
    new_order = Order(
        allergies = allergies_str,
        dietary_restriction=dietary_restrictions_str,
        location=location,
        delivery=delivery,
        user_id=user_id
    )

    db.session.add(new_order)
    db.session.commit()
    
    try:
        order_email(session.get('email'), session.get('user_name'), new_order)
    except Exception as e:
        # app.logger.error(f"Error sending confirmation email: {e}")
        flash("Error sending confirmation email. Please try again.", "danger")

    return redirect(url_for('views.index'))

    
@order_controller.route('/confirm_order/<int:order_id>', methods=['POST'])
def confirm_order(order_id):
    # Fetch the order from the database
    order = Order.query.get(order_id)
    if order:
        # Update the order status to "completed" and set the dispense time to now
        order.status = 'confirmed'
        order.dispense_time = datetime.now()
        db.session.commit()
        order_user = User.query.get(order.user_id)
        try:
            order_accepted_email(order_user.email, order_user.user_name, order)
            flash('order confirmed email', 'success')  
        except Exception as e:
            flash("Error sending acceptance email. Please try again.", "danger")   
            
    return redirect(url_for('views.index'))


@order_controller.route('/deny_order/<int:order_id>', methods=['POST'])
def deny_order(order_id):
    # Fetch the order from the database
    order = Order.query.get(order_id)
    
    if order:
        db.session.delete(order)
        db.session.commit()
        try:
            order_user = User.query.get(order.user_id)
            order_denied_email(order_user.email, order_user.user_name, order)
            flash('order denied email', 'success')  
        except Exception as e:
            flash("Error sending acceptance email. Please try again.", "danger")   
    return redirect(url_for('views.index'))


@order_controller.route('/fulfill_order/<int:order_id>', methods=['POST'])
def fulfill_order(order_id):
    # Fetch the order from the database
    order = Order.query.get(order_id)
    if order:
        db.session.delete(order)
        db.session.commit()
        try:
            user = User.query.get(session.get('user_id'))
            order_accepted_email(user.email, user.user_name, order)
            flash('order denied email', 'success')  
        except Exception as e:
            flash("Error sending acceptance email. Please try again.", "danger")   
    return redirect(url_for('views.index'))


@order_controller.route('/order_edit', methods=['POST'])
def order_edit():
        data = request.json  # Retrieve JSON data from the request
        order_id = data.get('order_id')
        allergies = data.get('allergies')
        dietary_restrictions = data.get('dietary_restrictions')

        # Fetch the order from the database
        order = Order.query.get(order_id)
        
        if order:
            # Update the order with the edited data
            order.allergies = ', '.join(allergies)
            order.dietary_restriction = ', '.join(dietary_restrictions)
            order.allergies = ', '.join(allergies) if allergies else 'None'
            order.dietary_restriction = ', '.join(dietary_restrictions) if dietary_restrictions else 'None'

            db.session.commit()
            flash('Order updated successfully', 'success')
        else:
            flash(f'Order not found - {order_id}', 'error')

        return jsonify({'success': True})
    



@order_controller.route('/order_delete', methods=['POST'])
def order_delete():
    # Retrieve the order ID from the JSON data sent in the request
    order_id = request.json.get('order_id')

    # Fetch the order from the database
    order = Order.query.get(order_id)
    
    if order:
        # Delete the order from the database
        db.session.delete(order)
        db.session.commit()
        flash('Order deleted successfully', 'success')
    else:
        flash('Order not found', 'error')
    
    # Redirect to the index page or any other appropriate page
    return jsonify({'success': True})

        

app/views/views.py
from flask import render_template, Blueprint, request, redirect, url_for, session, flash, jsonify
from datetime import datetime, timedelta
from ..models.user import User, Avatar, db
from ..models.order import Order
from ..ults.forms import LoginForm, RegisterForm
from sqlalchemy import desc, and_  # Import the desc method


views = Blueprint("views", __name__)


# routing for authentication


@views.route("/register", methods=["GET"])
def register():
    if 'user_id' in session:
        flash("user in session", "warning")
        return redirect(url_for("views.index"))
    else:
        form = RegisterForm(request.form)
        return render_template("register.html", form=form)


# @views.route("/login", methods=["GET", "POST"])
@views.route("/login", methods=["GET"])
def login():
    if 'user_id' in session:
        return redirect(url_for("views.index"))
    form = LoginForm(request.form)
    return render_template("login.html", form=form)


@views.route("/logout")
def logout():
    if "user_id" in session:
        user = session["user_name"]
        session.pop("user_id", None)
        session.pop("user_name", None)
        session.pop("email", None)
        session.pop("name", None)
        session.pop("role", None)
        flash(f"You have been logged out, {user}", "info")
        return redirect(url_for("views.index"))
    return redirect(url_for('views.login'))

# ROUTING FOR INDEX


@views.route("/", methods=["GET"])
def index():
    if 'user_id' in session:
        is_admin = session.get('role')
        if is_admin == 1:
            return redirect(url_for("views.admin"))
        user_id = session.get('user_id')
        user = User.query.get(user_id)
        orders_by_user_id = Order.query.filter_by(
            user_id=user_id).order_by(desc(Order.request_time)).all()
        
          # Check if the latest order was made more than 7 days ago
        today = datetime.now().date()
        latest_order = orders_by_user_id[0] if orders_by_user_id else None
        seven_days_ago = datetime.now() - timedelta(days=7)
        if latest_order and latest_order.request_time >= seven_days_ago:
            limit_reached = True
            days_left = (latest_order.request_time - seven_days_ago).days
        else:
            limit_reached = False
            days_left = (seven_days_ago - latest_order.request_time).days if latest_order else 7

        
        return render_template("index.html", user = user, orders_by_user_id=orders_by_user_id, days_left=days_left, limit_reached = limit_reached)
    else:
        # This should redirect to landing page (before logged in), instead of views.login
        return render_template("index.html")
        # return redirect(url_for("views.login"))


# ROUTING FOR USER
@views.route("/user_route", methods=["GET"])
def user_route():
    if 'user_id' in session:
        return redirect(url_for("views.user"))
    else:
        return redirect(url_for("views.login"))


@views.route("/user", methods=["GET"])
def user():
    if 'user_id' in session:
        # Retrieve user_id from session
        user_id = session.get('user_id')
        # Query the database to get the user information
        user = User.query.get(user_id)
        return render_template("user.html", user=user)
    else:
        flash("login to access this page", "warning")
        return redirect(url_for("views.index"))


@views.route("/campuses", methods=["GET"])
def campuses():
    return render_template("campuses.html")


@views.route("/faqs", methods=["GET"])
def faqs():
    return render_template("faqs.html")


@views.route("/about", methods=["GET"])
def about():
    return render_template("about.html")


@views.route("/contact", methods=["GET"])
def contact():
    return render_template("contact.html")


@views.route('/order_request', methods=['GET'])
def order_request():
    return redirect(url_for('views.index'))


@views.route('/admin', methods=['GET'])
def admin():
    if 'user_id' in session:
        is_admin = session.get('role')
        if is_admin == 1:
            user = User.query.get(session['user_id'])
            pending_delivery_orders = Order.query.filter(and_(
                Order.status == 'pending', Order.delivery == True)).order_by(Order.request_time).all()

            pending_pickup_orders = Order.query.filter(and_(
                Order.status == 'pending', Order.delivery == False)).order_by(Order.request_time).all()

            completed_orders = Order.query.filter(
                Order.status != 'pending').all()
            # Fetch avatar URLs for users associated with orders
            for order in pending_delivery_orders + pending_pickup_orders + completed_orders:
                order.user_avatar_url = order.user.avatar if order.user else None

            return render_template("admin.html", user=user, PDO=pending_delivery_orders, PPO=pending_pickup_orders, CO=completed_orders)

    flash("unauthorized access", "danger")
    return redirect(url_for("views.index"))


@views.route('/api/order/<order_id>', methods=['GET'])
def get_order(order_id):
    # Fetch order data from the database based on order_id
    order = Order.query.get(order_id)
    if order:
        # Convert order data to JSON format and return
        return jsonify({
            'id': order.id,  
            'allergies': order.allergies,
            'dietary_restriction': order.dietary_restriction,    
            'allergies_options': ['nuts', 'milk', 'shellfish', 'soy', 'eggs', 'wheat'],
            'dietary_restriction_options': ['vegetarian', 'vegan', 'gluten-free', 'lactose-free', 'halal', 'kosher']
        })
    else:
        return jsonify({'error': 'Order not found'}), 404

app/templates/partials/_header.html
<nav
	class="navbar navbar-dark bg-dark fixed-top"
	style="opacity: 0.9; padding: 10px; position: relative"
>
	<div class="container-fluid">
		<a class="navbar-brand" id="nav-logo" href="{{ url_for('views.index') }}"
			><h2>Pantry Pilot</h2></a
		>
		<button
			class="navbar-toggler"
			type="button"
			data-bs-toggle="offcanvas"
			data-bs-target="#offcanvasDarkNavbar"
			aria-controls="offcanvasDarkNavbar"
			aria-label="Toggle navigation"
		>
			<span class="navbar-toggler-icon"></span>
		</button>
		<div
		style = "width: 250px;"
			class="offcanvas offcanvas-end text-bg-dark"
			tabindex="-1"
			id="offcanvasDarkNavbar"
			aria-labelledby="offcanvasDarkNavbarLabel"
		>
			<div class="offcanvas-header">
				{% if 'user_id' in session %}
				<a
					class="btn btn-outline-danger mx-2"
					style="position: relative; margin: 0"
					href="{{ url_for('views.logout') }}"
					>Logout</a
				>
				<!-- Add other content or actions for authenticated users -->
				{% else %}
				<!-- User is not in session -->
				<h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Menu</h5>
				<!-- Add login form or other content for non-authenticated users -->
				{% endif %}
				<a href="{{ url_for('views.user_route') }}"
					><img src="/static/logos/user-white.svg" alt="user-logo"
				/></a>
				<!-- <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button> -->
			</div>
			<div class="offcanvas-body" >
				<ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
					
					<li class="nav-item">
						<a
							class="nav-link active"
							aria-current="page"
							href="{{ url_for('views.index') }}"
							>Home</a
						>
					</li>
					<li class="nav-item">
						<a
							class="nav-link active"
							aria-current="page"
							href="{{ url_for('views.campuses') }}"
							>Participating Campuses</a
						>
					</li>
					<li class="nav-item">
						<a
							class="nav-link active"
							aria-current="page"
							href="{{ url_for('views.about') }}"
							>About</a
						>
					</li>
					<li class="nav-item">
						<a
							class="nav-link active"
							aria-current="page"
							href="{{ url_for('views.contact') }}"
							>Contact Us</a
						>
					</li>
					<!-- commenting out just in case we want to implement a dropdown in the side menu
					<li class="nav-item dropdown">
						<a
							class="nav-link dropdown-toggle"
							href="#"
							role="button"
							data-bs-toggle="dropdown"
							aria-expanded="false"
						>
							Testing2
						</a>
						<ul class="dropdown-menu dropdown-menu-dark">
							<li><a class="dropdown-item" href="#">Action</a></li>
							<li><a class="dropdown-item" href="#">Another action</a></li>
							<li>
								<hr class="dropdown-divider" />
							</li>
							<li><a class="dropdown-item" href="#">Something else here</a></li>
						</ul>
					</li>
					-->
				</ul>
			</div>
		</div>
	</div>
</nav>

app/templates/partials/_info.html
<link
	rel="stylesheet"
	href="{{ url_for('static', filename='css/partials/_info.css') }}"
/>

<div class="info-container">
	<div class="profile">
		{% if user.avatar %}
		<img
			id="avatar"
			src="{{ url_for('static', filename='avatars/' + user.avatar.avatar_url_l) }}"
			alt="Avatar"
		/>
		{% else %}
		<div
			style="background: url({{ url_for('static', filename='logo.jpg') }}) center center/cover;"
		></div>
		{% endif %}
	</div>
	<div class="user-info">
		<h2>{{ user.user_name }}</h2>
		<p>Email: {{ user.email }}</p>
		<!-- Add more user information here -->
	</div>
</div>

app/templates/partials/_order_detail_modal.html
<div
	class="modal fade"
	id="orderDetailsModal{{ order.id }}"
	tabindex="-1"
	role="dialog"
	aria-labelledby="orderDetalsModalTitle"
	aria-hidden="true"
>
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLongTitle">
					{{ order.user.user_name }} -
					{{order.request_time.strftime('%d-%m-%Y')}}
				</h5>
				<button
					type="button"
					class="close"
					data-dismiss="modal"
					aria-label="Close"
				>
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<p><strong>Allergies</strong> : {{ order.allergies }}</p>
				<p><strong>Dietary Restriction</strong> : {{ order.dietary_restriction }}</p>
			</div>
			<div class="modal-footer">
				
				<form
					id="confirmOrderForm"
					action="{{ url_for('order_controller.confirm_order', order_id=order.id) }}"
					method="POST"
				>
					<button class="btn btn-primary" type="submit">Confirm Order</button>
				</form>
				<form
					id="confirmOrderForm"
					action="{{ url_for('order_controller.deny_order', order_id=order.id) }}"
					method="POST"
				>
					<button class="btn btn-danger" type="submit">Deny Order</button>
				</form>
			</div>
		</div>
	</div>
</div>

app/templates/partials/_orders.html
<link
	rel="stylesheet"
	href="{{ url_for('static', filename='css/partials/_orders.css') }}"
/>

<!-- order_request_form.html -->
<div class="orders-container">
	<div class="row justify-content-center">
		<div class="col">
			<div class="order-box mt-3 shadow" style="opacity: 0.8">
				<div class="card-body py-2 px-md-1">
					<h2 class="text-center mb-4 ">Request Orders</h2>

					<!-- Order Form -->
					<form
						method="POST"
						action="{{url_for('order_controller.order_request')}}"
					>
						<div class="allergies-container ">
							<h6>Do you have any food allergies?</h6>
							<ul class="checkboxes ">
								<li>
									<input type="checkbox" name="allergies" value="nuts" /> Nuts
								</li>
								<li>
									<input type="checkbox" name="allergies" value="milk" /> Milk
								</li>
								<li>
									<input type="checkbox" name="allergies" value="shellfish" />
									Shellfish
								</li>
								<li>
									<input type="checkbox" name="allergies" value="soy" /> Soy
								</li>
								<li>
									<input type="checkbox" name="allergies" value="eggs" /> Eggs
								</li>
								<li>
									<input type="checkbox" name="allergies" value="wheat" /> Wheat
								</li>
								
							</ul>
						</div>

						<div class="restrictions-container">
							<h6>Do you have any dietary restrictions?</h6>
							<ul class="checkboxes">
								<li>
									<input
										type="checkbox"
										name="dietary_restriction"
										value="vegetarian"
									/>
									Vegetarian
								</li>
								<li>
									<input
										type="checkbox"
										name="dietary_restriction"
										value="vegan"
									/>
									Vegan
								</li>
								<li>
									<input
										type="checkbox"
										name="dietary_restriction"
										value="gluten-free"
									/>
									Gluten-Free
								</li>
								<li>
									<input
										type="checkbox"
										name="dietary_restriction"
										value="lactose-free"
									/>
									Lactose-Free
								</li>
								<li>
									<input
										type="checkbox"
										name="dietary_restriction"
										value="halal"
									/>
									Halal
								</li>
								<li>
									<input
										type="checkbox"
										name="dietary_restriction"
										value="kosher"
									/>
									Kosher
								</li>
								
							</ul>
						</div>

						<div>
							<h6>How do you want to receive your order?</h6>
						</div>
						
						<div class="order-type-buttons btn-group btn-group-toggle" style="display:block" data-toggle="buttons">
							<label class="btn btn-secondary active" for="pickup" checked>
								<input type="radio" name="delivery" id="pickup" value = "0" autocomplete="off" checked> Pickup
							</label>
							<label class="btn btn-secondary" for="deliver">
								<input type="radio" name="delivery" id="deliver" value = "1" autocomplete="off"> Deliver
							</label>
						</div>
						
						<div id="delivery-address" style="display: none, margin: 5px 10px; padding: 5px;">
							<input type="text" class="form-control" disabled  name="location" id="addressInput" placeholder="Enter delivery address">
						</div>
						
						<button
							type="submit"
							id = "submitBtn"
							class="btn btn-primary btn-block mx-3 col-md-5  "
						>
							Submit Request
						</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="order-history-box">
	<div class="row justify-content-center">
		<div class="col">
			<div class="order-box mt-3 shadow">
				<div class="card-body py-2 px-md-1">
					<div class="d-flex justify-content-end">
						<div
							class="btn-group btn-group-md"
							role="group"
							aria-label="Small button group"
						>
							<button
								type="button"
								id="deliveryBtn"
								class="btn btn-outline-primary"
							>
								delivery
							</button>
							<button
								type="button"
								id="pickupBtn"
								class="btn btn-outline-primary"
							>
								pickup
							</button>
							<button
								type="button"
								id="confirmBtn"
								class="btn btn-outline-success"
							>
								processing
							</button>
							<button
								type="button"
								id="completeBtn"
								class="btn btn-outline-success"
							>
								completed
							</button>
						</div>
					</div>
				</div>
		
					<!-- This content will be displayed in the modal -->
					<div class="list-group" id="orderList">
						{% for order in orders_by_user_id %}
						<div class = "list-item">
							<a data-toggle="modal" data-target="#orderDetailModal"
								href="#"
								data-order-id="{{ order.id }}"
								data-delivery="{{ order.delivery }}"
								data-status="{{ order.status }}"
								data-allergies="{{ order.allergies }}"
								data-dietary-restriction="{{ order.dietary_restriction }}"
								data-request-time="{{ order.request_time }}"
								data-dispense-time="{{ order.dispense_time }}"
								data-location="{{ order.location }}"
								class="list-group-item list-group-item-action my-1"
								style="background-color: {% if order.status == 'pending' %}rgba(187, 231, 231, 0.7);{%else%}
								rgba(63, 146, 99, 0.825);;{% endif %}"
								>{{ order.request_time.strftime('%d-%m-%Y') }}
							</a>
						</div>						
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- order_request_form.html -->
<div class="modal fade" id="orderDetailModal" tabindex="-1" role="dialog" aria-labelledby="orderDetailModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="orderDetailModalLabel">Order #<span id="orderId"></span> - <span id="headerNote"></span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Populate modal body with order details -->
				<span hidden id="status"></span>
				<span hidden id="location"></span>
				<span hidden id="delivery"></span>
				<span hidden id="requestTime"></span>
				<span hidden id="dispenseTime"></span>
                
                <h5><strong>Allergies:&emsp;&emsp;&emsp;</strong> <span id="allergies"></span></h5>
                <h5><strong>Dietary Restr:&emsp; </strong><span id="dietaryRestriction"></span></h5>
				
                <!-- Conditional button based on status -->
            </div>
            <div class="modal-footer">
				<button type="button" id="editButton" style="display: none;"   data-order-id="" class="btn btn-primary">Edit</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <!-- Add additional buttons or actions if needed -->
            </div>
        </div>
    </div>
</div>

<!-- EDIT MODAL -->
<div class="modal fade" id="editModal" tabindex="" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel" style="font-size: 1.2em;">Edit Order Details <span id="orderIdDisplay"></span></h5> <!-- Increase font size -->
            </div>
            <div class="modal-body" style=" display: flex;
			justify-content: center; padding: 10px; width: auto;"> <!-- Increase padding -->
                <input type="hidden" id="orderIdInput">

				
                <div class="form-group editB">
					<strong><label for="allergiesInput"  class="float-right">Allergies:</label></strong>
                    <ul id="allergiesList"></ul>
                </div>
                <div class="form-group editB">
					<strong><label for="dietaryRestrictionInput" class="float-right">Dietary Restrictions:</label></strong>
                    <ul id="dietaryList"  ></ul>
                </div>
                <!-- Add other fields for editing -->
            </div>
			<div class="modal-footer">
				<button type="button " id="saveBtn" class="btn btn-primary float-right ">Save Changes</button>
				<button type="button " id="deleteBtn" class="btn btn-danger float-right ">Delete Order</button>
			</div>
        </div>
               
    </div>
</div>


<!-- JavaScript to handle modal content -->
<script>
	document.addEventListener("DOMContentLoaded", function() {
        // Get the labels
        var pickupLabel = document.querySelector('[for="pickup"]');
        var deliverLabel = document.querySelector('[for="deliver"]');

        // Get the delivery address input
        var deliveryAddressDiv = document.getElementById("delivery-address");
        var addressInput = document.getElementById("addressInput");

        // Add event listener to the labels
        deliverLabel.addEventListener("click", function() {
            // If "Deliver" option is clicked, show the delivery address input field
            deliveryAddressDiv.style.display = "block";
            addressInput.disabled = false;
        });

        pickupLabel.addEventListener("click", function() {
            // If "Pickup" option is clicked, hide the delivery address input field
            deliveryAddressDiv.style.display = "none";
            addressInput.disabled = true;
        });
    });

		//CHecking limit_reached by last order
		{/* 
			document.addEventListener("DOMContentLoaded", function() {
			var limitReached = {% if limit_reached %}true{% else %}false{% endif %};
			var limitResetDays = {{ days_left }};
			var submitBtn = document.getElementById('submitBtn');
			if (limitReached) {
				var inputFields = document.querySelectorAll('input');
				inputFields.forEach(function(input) {
					input.disabled = true;
				});
				var radioLabels = document.querySelectorAll('.order-type-buttons label');
				radioLabels.forEach(function(label) {
					label.classList.add('disabled');
				});
	
				submitBtn.textContent = `Days Left: ${limitResetDays}`;
            	submitBtn.disabled = true;
				submitBtn.classList.add('btn-danger')
			}
		});
		 
		*/}
	
	document.addEventListener("DOMContentLoaded", function() {
        var orderLinks = document.querySelectorAll('.list-group-item');

        orderLinks.forEach(function(link) {
            link.addEventListener('click', function() {
                var orderId = this.getAttribute('data-order-id');
                var delivery = this.getAttribute('data-delivery');
                var status = this.getAttribute('data-status');
				var allergies = this.getAttribute('data-allergies');
				var dietaryRestriction = this.getAttribute('data-dietary-restriction');
				var requestTime = this.getAttribute('data-request-time');
				var dispenseTime = this.getAttribute('data-dispense-time');
				var location = this.getAttribute('data-location');
	
				
                document.getElementById('orderId').textContent = orderId;
                document.getElementById('delivery').textContent = delivery;
                document.getElementById('status').textContent = status;
				document.getElementById('allergies').textContent = allergies;
				document.getElementById('dietaryRestriction').textContent = dietaryRestriction;
				document.getElementById('location').textContent = location;
				document.getElementById('dispenseTime').textContent = dispenseTime;
				document.getElementById('requestTime').textContent = requestTime;
				editButton.setAttribute('data-order-id', orderId);
				document.getElementById('headerNote').textContent = status;
				
				

                // Update conditional button visibility and status handling when the modal is opened
                $('#orderDetailModal').on('shown.bs.modal', function () {
                    if (status === 'pending') {
						var editButton = document.getElementById('editButton');
                        editButton.style.display = 'block';
                        editButton.disabled = false;
                    } else {
                        var editButton = document.getElementById('editButton');
                        editButton.style.display = 'none';
                        editButton.disabled = true;
                    }
                });
				
            });
        });
    });
</script>


<script src="{{ url_for('static', filename='js/order_request.js') }}"></script>
<script src="{{ url_for('static', filename='js/order_edit.js') }}"></script>
<script src="{{ url_for('static', filename='js/order_history.js') }}"></script>

app/templates/partials/_toast.html
<link
	rel="stylesheet"
	href="{{ url_for('static', filename='css/partials/_toast.css') }}"
/>

<!--I think this is not working properly because the flashed messages never leave fully-->

{% with messages = get_flashed_messages(with_categories = True) %} {% if
messages %} {% for category, msg in messages %}
<div
	class="alert {% if category == 'info' %} alert-info {% elif category == 'success' %} alert-success {% elif category == 'error' %} alert-danger {% else %} alert-warning {% endif %} alert-success alert-dismissible fade show"
	id="hideMe"
	data-bs-dismiss="alert"
	role="alert"
>
	<strong>{{ msg }}</strong>
</div>

{% endfor %} {% endif %} {% endwith %}