app/models/user.py
from flask_avatars import Identicon  # Import Identicon style from Flask Avatars
from flask import current_app
from . import db
import os
import string
from ..ults.randomString import random_string


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    user_name = db.Column(db.String(50), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)
    bio = db.Column(db.Text)
    is_admin = db.Column(db.Boolean, nullable=False, default=False)

    avatar = db.relationship('Avatar', backref='user', uselist=False)

    def check_password(self, password):
        return password == self.password

    def generate_avatar(self):
        # Generate a random Identicon avatar URL
        avatar = Identicon()
        # Assuming you have a configuration variable for the save path
        path = current_app.config['AVATARS_SAVE_PATH']
        # Delete previous avatar files if they exist
        if self.avatar:
            previous_avatar_paths = [
                os.path.join(path, getattr(self.avatar, f'avatar_url_{size}'))
                for size in ['s', 'm', 'l']
            ]
            for previous_avatar_path in previous_avatar_paths:
                if os.path.exists(previous_avatar_path):
                    os.remove(previous_avatar_path)
        # Generate new avatar URLs for all three sizes
        fileNames = avatar.generate(text=random_string(5, self.user_name))
        # Assuming fileNames contains URLs for small, medium, and large avatars
        avatar_urls = fileNames[:3]
        # Create or update the avatar associated with the user
        if self.avatar:
            self.avatar.avatar_url_s, self.avatar.avatar_url_m, self.avatar.avatar_url_l = avatar_urls
        else:
            self.avatar = Avatar(
                user_id=self.id,
                avatar_url_s=avatar_urls[0],
                avatar_url_m=avatar_urls[1],
                avatar_url_l=avatar_urls[2]
            )
        db.session.commit()


class Avatar(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey(
        'user.id'), unique=True, nullable=False)
    avatar_url_s = db.Column(db.String(255), nullable=False)
    avatar_url_m = db.Column(db.String(255), nullable=False)
    avatar_url_l = db.Column(db.String(255), nullable=False)

app/controllers/auth_controller.py
from flask import render_template, Blueprint, request, redirect, url_for, session, flash
from ..models.user import User, db
from ..models.order import Order
from ..ults.forms import LoginForm, RegisterForm
from ..ults._emailAPI import register_email


# from app import app

auth_controller = Blueprint("auth_controller", __name__)


@auth_controller.route("/register", methods=["POST"])
def Register():
    form = RegisterForm(request.form)
    if form.validate():
        existing_username = User.query.filter_by(
            user_name=form.user_name.data).first()
        existing_email = User.query.filter_by(email=form.email.data).first()
        if existing_email or existing_username:
            flash("Email or Username has been used", "info")
            return render_template("register.html", form=form)
        else:
            # hashed_password = generate_password_hash(form.password.data, method="sha256")
            is_volunteer = bool(int(request.form.get('is_volunteer', 0)))             
            new_user = User(name=form.name.data, user_name=form.user_name.data,
                            email=form.email.data, password=form.password.data, is_admin = is_volunteer)
            db.session.add(new_user)
            db.session.commit()

            try:
                register_email(new_user.email, new_user.name,
                               new_user.user_name)
            except Exception as e:
                # app.logger.error(f"Error sending confirmation email: {e}")
                flash("Error sending registration email. Please try again.", "danger")

            flash(
                f"Registration successful...please log in!: {new_user.user_name}", "success")
            return redirect(url_for('views.login'))


@auth_controller.route("/login", methods=["POST"])
def Login():
    form = LoginForm(request.form)  # retrive form info from login page
    # if the user press login and the form is filled correcly
    if form.validate():
        # check if the user existed in database by user_name
        existing_username = User.query.filter_by(
            user_name=form.user_name.data).first()
        # if user DOES exist AND password is correct
        if existing_username and existing_username.check_password(form.password.data):

            # Store user information in the session (customize as needed)
            session['user_id'] = existing_username.id
            session['user_name'] = existing_username.user_name
            session['email'] = existing_username.email
            session['name'] = existing_username.name
            session['role'] = existing_username.is_admin

            session.permanent = True
            flash('Login successful!', 'success')
            return redirect(url_for('views.index'))

        else:
            flash('Invalid username or password. Please try again.', 'error')
            return redirect(url_for('views.login'))


@auth_controller.route('/generate_avatar/<int:user_id>')
def generate_avatar(user_id):
    if 'user_id' in session and user_id == session.get('user_id'):
        user = User.query.get(user_id)  
        if user:
            user.generate_avatar()
    return redirect(url_for('views.user'))

app/controllers/user_controller.py
from flask import render_template, Blueprint, request, redirect, url_for, session, flash
from ..models.user import User, db
from ..models.order import Order
from ..ults.forms import LoginForm, RegisterForm
from ..ults._emailAPI import register_email


user_controller = Blueprint("user_controller", __name__)


@user_controller.route("/user_edit", methods=["POST"])
def user_edit():
    if 'user_id' in session:
        user_id = session.get('user_id')
        new_bio = request.form.get('bio')
        user = User.query.get(user_id)
        user.bio = new_bio

        db.session.commit()
        return redirect(url_for("views.user"))
    else:
        return redirect(url_for("views.user"))

app/views/views.py
from flask import render_template, Blueprint, request, redirect, url_for, session, flash, jsonify
from datetime import datetime, timedelta
from ..models.user import User, Avatar, db
from ..models.order import Order
from ..ults.forms import LoginForm, RegisterForm
from sqlalchemy import desc, and_  # Import the desc method


views = Blueprint("views", __name__)


# routing for authentication


@views.route("/register", methods=["GET"])
def register():
    if 'user_id' in session:
        flash("user in session", "warning")
        return redirect(url_for("views.index"))
    else:
        form = RegisterForm(request.form)
        return render_template("register.html", form=form)


# @views.route("/login", methods=["GET", "POST"])
@views.route("/login", methods=["GET"])
def login():
    if 'user_id' in session:
        return redirect(url_for("views.index"))
    form = LoginForm(request.form)
    return render_template("login.html", form=form)


@views.route("/logout")
def logout():
    if "user_id" in session:
        user = session["user_name"]
        session.pop("user_id", None)
        session.pop("user_name", None)
        session.pop("email", None)
        session.pop("name", None)
        session.pop("role", None)
        flash(f"You have been logged out, {user}", "info")
        return redirect(url_for("views.index"))
    return redirect(url_for('views.login'))

# ROUTING FOR INDEX


@views.route("/", methods=["GET"])
def index():
    if 'user_id' in session:
        is_admin = session.get('role')
        if is_admin == 1:
            return redirect(url_for("views.admin"))
        user_id = session.get('user_id')
        user = User.query.get(user_id)
        orders_by_user_id = Order.query.filter_by(
            user_id=user_id).order_by(desc(Order.request_time)).all()
        
          # Check if the latest order was made more than 7 days ago
        today = datetime.now().date()
        latest_order = orders_by_user_id[0] if orders_by_user_id else None
        seven_days_ago = datetime.now() - timedelta(days=7)
        if latest_order and latest_order.request_time >= seven_days_ago:
            limit_reached = True
            days_left = (latest_order.request_time - seven_days_ago).days
        else:
            limit_reached = False
            days_left = (seven_days_ago - latest_order.request_time).days if latest_order else 7

        
        return render_template("index.html", user = user, orders_by_user_id=orders_by_user_id, days_left=days_left, limit_reached = limit_reached)
    else:
        # This should redirect to landing page (before logged in), instead of views.login
        return render_template("index.html")
        # return redirect(url_for("views.login"))


# ROUTING FOR USER
@views.route("/user_route", methods=["GET"])
def user_route():
    if 'user_id' in session:
        return redirect(url_for("views.user"))
    else:
        return redirect(url_for("views.login"))


@views.route("/user", methods=["GET"])
def user():
    if 'user_id' in session:
        # Retrieve user_id from session
        user_id = session.get('user_id')
        # Query the database to get the user information
        user = User.query.get(user_id)
        return render_template("user.html", user=user)
    else:
        flash("login to access this page", "warning")
        return redirect(url_for("views.index"))


@views.route("/campuses", methods=["GET"])
def campuses():
    return render_template("campuses.html")


@views.route("/faqs", methods=["GET"])
def faqs():
    return render_template("faqs.html")


@views.route("/about", methods=["GET"])
def about():
    return render_template("about.html")


@views.route("/contact", methods=["GET"])
def contact():
    return render_template("contact.html")


@views.route('/order_request', methods=['GET'])
def order_request():
    return redirect(url_for('views.index'))


@views.route('/admin', methods=['GET'])
def admin():
    if 'user_id' in session:
        is_admin = session.get('role')
        if is_admin == 1:
            user = User.query.get(session['user_id'])
            pending_delivery_orders = Order.query.filter(and_(
                Order.status == 'pending', Order.delivery == True)).order_by(Order.request_time).all()

            pending_pickup_orders = Order.query.filter(and_(
                Order.status == 'pending', Order.delivery == False)).order_by(Order.request_time).all()

            completed_orders = Order.query.filter(
                Order.status != 'pending').all()
            # Fetch avatar URLs for users associated with orders
            for order in pending_delivery_orders + pending_pickup_orders + completed_orders:
                order.user_avatar_url = order.user.avatar if order.user else None

            return render_template("admin.html", user=user, PDO=pending_delivery_orders, PPO=pending_pickup_orders, CO=completed_orders)

    flash("unauthorized access", "danger")
    return redirect(url_for("views.index"))


@views.route('/api/order/<order_id>', methods=['GET'])
def get_order(order_id):
    # Fetch order data from the database based on order_id
    order = Order.query.get(order_id)
    if order:
        # Convert order data to JSON format and return
        return jsonify({
            'id': order.id,  
            'allergies': order.allergies,
            'dietary_restriction': order.dietary_restriction,    
            'allergies_options': ['nuts', 'milk', 'shellfish', 'soy', 'eggs', 'wheat'],
            'dietary_restriction_options': ['vegetarian', 'vegan', 'gluten-free', 'lactose-free', 'halal', 'kosher']
        })
    else:
        return jsonify({'error': 'Order not found'}), 404

app/templates/about.html
{% extends "partials/_layout.html" %} {% include "partials/_header.html" %}
{%block content%}
<div class="container mt-4">
	<div class="card">
		<div class="card-header">
			<h5>Project Overview</h5>
		</div>
		<div class="card-body">
			<p class="card-info">
				Pantry Pilot is an initiative that partners with local universities to
				combat student hunger and food insecurity. Our innovative app creates a
				safety net for students in need, making it easy for them to request food
				assistance. A dedicated network of volunteers provides nutritious meals
				and access to campus food pantries, addresses accessibility challenges,
				reduces food waste, and promotes community engagement within educational
				institutions. The program allows students to focus on learning and
				thrive while ensuring that no student goes hungry. The program is
				designed to ensure that no student goes hungry, minimize food waste,
				strengthen community ties, and help students succeed academically.
			</p>
			<img
				src="static/img/PantryPilotLogo.png"
				alt="Pantry Pilot Logo"
				class="center"
			/>
		</div>
	</div>
</div>
<style>
	.center {
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 25%;
  }
</style>

{%endblock%}

app/templates/admin.html
<link
	rel="stylesheet"
	href="{{ url_for('static', filename='css/admin.css') }}"
/>
{% extends "partials/_layout.html" %} {% include "partials/_header.html" %}
{%block content %}
<div class="container" style="width: 70%; background-color: white">
	<div class="row justify-content-center">
		<!-- Info box on the left -->
		{% include "partials/_info.html" %}

		<!-- Container on the right -->
		<div class="col-md-8" id="order-lists">
			<h2>Pending Delivery Orders</h2>

			<div class="scrollable-container">
				<div class="scrollable-cards">
					{% for order in PDO %}
					<div
						class="col-mb-5 m-1"
						data-order-id="{{ order.id }}"
						type="button"
						data-toggle="modal"
						data-target="#orderDetailsModal{{ order.id }}"
					>
						<div class="card mb-4 m-1">
							<div class="card-body p-1">
								<div class="d-flex align-items-center px-1">
									<img
										id="avatar"
										class="avatar"
										src="{{ url_for('static', filename='avatars/' + order.user_avatar_url.avatar_url_s) }}"
										alt="Avatar"
									/>
									<div class="d-grid">
										<h5 class="card-text">{{ order.user.user_name }}</h5>
										<h6 class="card-date">
											{{ order.request_time.strftime('%d-%m-%Y') }}
										</h6>
									</div>
								</div>
							</div>
						</div>
					</div>
					{% include "partials/_order_detail_modal.html" %}
					{% endfor %}
				</div>
			</div>

			<h2>Pending Pickup Orders</h2>
			<div class="scrollable-container">
				<div class="scrollable-cards">
					{% for order in PPO %}
					<div
						class="col-mb-5 m-1"
						data-order-id="{{ order.id }}"
						type="button"
						data-toggle="modal"
						data-target="#orderDetailsModal{{ order.id }}"
					>
						<div class="card mb-4 m-1">
							<div class="card-body p-1">
								<div class="d-flex align-items-center px-1">
									<img
										id="avatar"
										class="avatar"
										src="{{ url_for('static', filename='avatars/' + order.user_avatar_url.avatar_url_s) }}"
										alt="Avatar"
									/>
									<div class="d-grid">
										<h5 class="card-text">{{ order.user.user_name }}</h5>
										<h6 class="card-date">
											{{ order.request_time.strftime('%d-%m-%Y') }}
										</h6>
									</div>
								</div>

								<!-- Add more details as needed -->
							</div>
						</div>
					</div>

					{% include "partials/_order_detail_modal.html" %} {%endfor %}
				</div>
			</div>

			<h2>Processing Orders</h2>
			<div class="scrollable-container">
				<div class="scrollable-cards">
					{% for order in CO %}
					<div
						class="col-mb-5 m-1"
						type="button"
						data-toggle="modal"
						data-target="#orderDetailsModal"
					>
						<div class="card mb-4 m-1">
							<div class="card-body p-1">
								<div class="d-flex align-items-center px-1">
									<img
										id="avatar"
										class="avatar"
										src="{{ url_for('static', filename='avatars/' + order.user_avatar_url.avatar_url_s) }}"
										alt="Avatar"
									/>
									<div class="d-grid">
										<h5 class="card-text">{{ order.user.user_name }}</h5>
										<h6 class="card-date">
											{{ order.request_time.strftime('%d-%m-%Y') }}
										</h6>
									</div>
								</div>

								<!-- Add more details as needed -->
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
			<!-- Modal -->
			
		</div>
	</div>
</div>

<script>

	

	$(document).ready(function () {
		$('[data-toggle="popover"]').popover();
	});
	$('.popover-dismiss').popover({
		trigger: 'focus',
	});
</script>

{% endblock %}

app/templates/campuses.html
{% extends "partials/_layout.html" %}
{% include "partials/_header.html" %}

{%block content%}
<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h5>Participating Campuses</h5>
        </div>
        <div class="card-body">
            <p class="card-info">
                As of now, Pantry Pilot is only configured to work with the University of Illinois at Chicago (UIC) located at 1200 W Harrison St, Chicago. Our volunteers will deliver to any UIC dorm or UIC affiliated housing complex.</p>
                <img src="https://business.uic.edu/wp-content/uploads/sites/91/2018/06/research-1090x595.jpg" alt="UIC Campus Image" width="800" height="500" class="center">
        </div>
    </div>
</div>


<!-- Custom CSS -->
<style>
	.center {
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 100%;
  }
</style>
{%endblock%}

app/templates/contact.html
{% extends "partials/_layout.html" %}
{% include "partials/_header.html" %}

{%block content%}
<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h5>Contact Us</h5>
        </div>
        <div class="card-body">
            <p class="card-info">
                If you are a represenative from another unvierstiy looking to partner with Pantry Pilot or have any other inquiries, please contact us at pantrypilotUIC@gmail.com</p>
        </div>
    </div>
</div>

{%endblock%}

app/templates/index.html
<link
	rel="stylesheet"
	href="{{ url_for('static', filename='css/index.css') }}"
/>

{% extends "partials/_layout.html" %} {% include "partials/_header.html" %}
{%block content%} 
{% if 'user_id' in session %}
<!-- User is in session -->
<!-- Add other content or actions for authenticated users -->
<div class="main-container">
	{% include "partials/_info.html" %}
	<div class="right-container">
		{% include "partials/_orders.html" %}
	</div>
</div>
{%else %}
<!-- User is not in session -->
{% include "welcome.html" %}

<!-- Add login form or other content for non-authenticated users -->

{% endif %}
{%endblock%}

app/templates/login.html
<link
	rel="stylesheet"
	href="{{ url_for('static', filename='css/partials/_auth.css') }}"
/>

{% extends "partials/_layout.html" %} {% include "partials/_header.html" %} {%
block content %}
<div class="login_header">
	<h1>Login Page</h1>
</div>
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-4">
			<div class="card mt-3 shadow" style="opacity: 0.8">
				<div class="card-body py-4 px-md-4">
					<!-- Registration Form -->
					<form
						method="POST"
						action="{{ url_for('views.login') }}"
						enctype="multipart/form-data"
					>
						{{ form.hidden_tag() }}

						<div class="form-group">
							<!-- User_name input -->
							<div class="form-outline mb-3">
								{{ form.user_name.label(class="form-label") }} {{
								form.user_name(class="form-control") }} {% for error in
								form.user_name.errors %}
								<span class="text-danger">{{ error }}</span>
								{% endfor %}
							</div>

							<!-- Password input -->
							<div class="form-outline mb-3">
								{{ form.password.label(class="form-label") }} {{
								form.password(class="form-control") }} {% for error in
								form.password.errors %}
								<span class="text-danger">{{ error }}</span>
								{% endfor %}
							</div>
						</div>

						<div class="row">
							<div class="col-md-7">
								<button type="submit" class="btn btn-success btn-block mb-3">
									Login
								</button>
							</div>

							<div class="col-md-5">
								<a
									href="{{  url_for('views.register') }}"
									class="btn btn-primary btn-block mb-3"
								>
									Create Account
								</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Add any additional scripts or links to external JS files if needed -->
{% endblock %}

app/templates/register.html
<link
	rel="stylesheet"
	href="{{ url_for('static', filename='css/partials/_auth.css') }}"
/>

{% extends "partials/_layout.html" %} {% include "partials/_header.html" %} {%
block content %}
<div class="register_header">
	<h1>Sign Up</h1>
</div>
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-4">
			<div class="card mt-3 shadow" style="opacity: 0.8">
				<div class="card-body py-4 px-md-4">
					<!-- Registration Form -->
					<form method="POST" action="" enctype="multipart/form-data">
						{{ form.hidden_tag() }}

						<div class="row">
							<!-- User_name and Name inputs on the same row -->
							<div class="form-outline mb-3 col-md-6">
								{{ form.user_name.label(class="form-label") }} {{
								form.user_name(class="form-control") }} {% for error in
								form.user_name.errors %}
								<span class="text-danger">{{ error }}</span>
								{% endfor %}
							</div>

							<div class="form-outline mb-3 col-md-6">
								{{ form.name.label(class="form-label") }} {{
								form.name(class="form-control") }} {% for error in
								form.name.errors %}
								<span class="text-danger">{{ error }}</span>
								{% endfor %}
							</div>

							<!-- Email input on a separate row -->
							<div class="form-outline mb-3 col-md-12">
								{{ form.email.label(class="form-label") }} {{
								form.email(class="form-control") }} {% for error in
								form.email.errors %}
								<span class="text-danger">{{ error }}</span>
								{% endfor %}
							</div>

							<!-- Password and Confirm Password inputs on the same row -->
							<div class="form-outline mb-3 col-md-6">
								{{ form.password.label(class="form-label") }} {{
								form.password(class="form-control") }} {% for error in
								form.password.errors %}
								<span class="text-danger">{{ error }}</span>
								{% endfor %}
							</div>

							<div class="form-outline mb-3 col-md-6">
								{{ form.repassword.label(class="form-label") }} {{
								form.repassword(class="form-control") }} {% for error in
								form.repassword.errors %}
								<span class="text-danger">{{ error }}</span>
								{% endfor %}
							</div>

							<div id="is-volunteer" class="form-check form-switch">
								<input
									class="form-check-input"
									type="checkbox"
									id="flexSwitchCheckChecked"
									name="is_volunteer"
                                    value="1" 
                                    checked
								/>
                                <input type="hidden" name="is_volunteer" value="0"> <!-- Hidden input for unchecked -->
								<label class="form-check-label" for="flexSwitchCheckChecked"
									>Volunteer?</label
								>
							</div>

							<!-- Buttons in the same row but adjusted position -->
							<div class="col-md-7">
								<button type="submit" class="btn btn-success btn-block mb-3">
									Register
								</button>
							</div>

							<div class="col-md-5">
								<a
									href="{{  url_for('views.login') }}"
									class="btn btn-primary btn-block mb-3"
								>
									Go to Login
								</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Add any additional scripts or links to external JS files if needed -->
{% endblock %}

app/templates/user.html
{% extends "partials/_layout.html" %} {% include "partials/_header.html" %}
{%block content%}
<!-- app/templates/user.html -->

<!-- Profile page -->
<div class="container mt-4">
	<div class="row justify-content-center">
		<div class="col-md-6">
			<div class="card">
				<div class="card-body">
					<div class="row align-items-center">
						<!-- Profile photo column -->
						<div class="col-auto">
							<div class="profile-photo">
								{% if user.avatar %}
								<img
									id="avatar"
									src="{{ url_for('static', filename='avatars/' + user.avatar.avatar_url_l) }}"
									alt="Avatar"
								/>
								{% else %}
								<div
									style="background: url({{ url_for('static', filename='logo.jpg') }}) center center/cover; width: 100%; height: 100%; border-radius: 50%"
								></div>
								{% endif %}
								<a
									href="#"
									class="edit-profile-icon"
									data-bs-toggle="modal"
									data-bs-target="#editBioModal"
									><img src="/static/logos/edit-icon.svg" alt="edit-logo"
								/></a>
								<a
									id="avatar-change"
									href="{{ url_for('auth_controller.generate_avatar', user_id = user.id) }}"
									><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-clockwise" viewBox="0 0 16 16" stroke-width="3">
										<path fill-rule="evenodd" d="M8 3a5 5 0 1 0 4.546 2.914.5.5 0 0 1 .908-.417A6 6 0 1 1 8 2z"/>
										<path d="M8 4.466V.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384L8.41 4.658A.25.25 0 0 1 8 4.466"/>
									  </svg>
								</a>
							</div>
						</div>
						<!-- User information column -->
						<div class="col">
							<h2 class="card-title">{{ user.name }} - UIC</h2>
							<h4 class="card-text">{{ user.email }}</h4>
							<h5 class="bio">Bio: {{user.bio}}</h5>
							<!-- Add more user information fields as needed -->
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Edit Bio Modal -->
<div
	class="modal fade"
	id="editBioModal"
	tabindex="-1"
	aria-labelledby="editBioModalLabel"
	aria-hidden="true"
>
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="editBioModalLabel">Edit Bio</h5>
				<button
					type="button"
					class="btn-close"
					data-bs-dismiss="modal"
					aria-label="Close"
				></button>
			</div>
			<div class="modal-body">
				<form
					id="editBioForm"
					method="POST"
					action="{{ url_for('user_controller.user_edit') }}"
				>
					<div class="mb-3">
						<label for="userNameInput" class="form-label"
							>User Name - (need work- authenticate for existing
							user_name)</label
						>
						<input
							type="text"
							class="form-control"
							id="userNameInput"
							disabled
							value="{{ user.user_name }}"
						/>

						<label for="bioInput" class="form-label">Bio</label>
						<input
							type="text"
							class="form-control"
							id="bioInput"
							name="bio"
							placeholder="Enter your bio"
						/>
						<div id="bioInputError" class="invalid-feedback">
							Bio cannot be empty
						</div>
					</div>
					<button type="submit" class="btn btn-primary">Save changes</button>
				</form>
			</div>
		</div>
	</div>
</div>

<script src="{{ url_for('static', filename='js/user_edit.js') }}"></script>

<!-- Custom CSS -->
<style>
	.profile-photo,
	#avatar {
		width: 150px;
		height: 150px;
		background-color: #f0f0f0;
		border-radius: 50%;

		margin-right: 20px; /* Space between profile photo and user information */
	}

	.edit-profile-icon {
		position: absolute;
		scale: 1.2;
		top: 10;
		right: 10;
		background-color: #ffffff;
		border-radius: 50%;
		padding: 5px;
	}

	#avatar-change{
		position: absolute;
		color: black;
		top: 75%;
		left:22%;	
	}
</style>

{%endblock%}

app/templates/welcome.html
<link
	rel="stylesheet"
	href="{{ url_for('static', filename='css/welcome.css') }}"
/>

<section class="hero">
    <div class="hero-content">
        <img id="hero-img" src="static/img/hero1.jpg" alt="hero">
            <div class="text-overlay line1">UIC Student</div>
            <div class="text-overlay line2">&</div>
            <div class="text-overlay line3">Food insecure?</div>
            <div class="text-overlay line4">we're here to help...</div>
    </div>
</section>

<section class="missions">
    <div class="missions-content">

        <div class="missions-body">
            <div class="right">
                <div class="text-m l1"> Our Mission</div>
                <img id="mission-img" src="static/img/mission.jpg" alt="mission img">
                <!--<div class="text-m l4"> just Broke</div>-->
            </div>
            <div class="left">
                <p class="text-m l2">Pantry Pilot is an initiative that partners with local universities to combat student hunger and food insecurity. Our innovative app creates a safety net for students in need, making it easy for them to request food assistance. A dedicated network of volunteers provides nutritious meals and access to campus food pantries, addresses accessibility challenges, reduces food waste, and promotes community engagement within educational institutions. The program allows students to focus on learning and thrive while ensuring that no student goes hungry. The program is designed to ensure that no student goes hungry, minimize food waste, strengthen community ties, and help students succeed academically.</p>
                <!--<div class="text-m l3"> No More Hungry...</div>-->
            </div>

        </div>
    </div>
</section>
<section class="parallax">
    <div class="parallax-inner">
        <h2 class="parallax-text">PantryPilot</h2>
    </div>
</section>
<section class="campus">
    <div class="campus-content">
        
    </div>
</section>

<section class="about">

</section>